### ISSUE TITLE
在数据量稍微大一些的时候代码会出问题！

### ISSUE THREAD

**Issue by guiyang882** [vickyqi/StudyBuddy#2]
输入的是这个字符串的时候 
nm0001: after this er little performance [1.0] som

**Comment by guiyang882** [comment]
Connected to the target VM, address: '127.0.0.1:59275', transport: 'socket'
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
    at suffixtree.SuffixTree.find(SuffixTree.java:162)
    at suffixtree.SuffixTree.build(SuffixTree.java:21)
    at suffixtree.SuffixTree.main(SuffixTree.java:247)
nm0001: after this er little performance [1.0] som
Disconnected from the target VM, address: '127.0.0.1:59275', transport: 'socket'

**Comment by guiyang882** [comment]
} else if (current.chars[activePoint.length] == w) {// 有活动边，则在活动边上查找

问题定位在这一行！
